services:
  ol:
    build: . 
    image: open-lambda:latest
    privileged: true
    security_opt:
    - seccomp=unconfined
    - apparmor=unconfined
    working_dir: /workspace
    environment:
      WORKER_NAME: default
      GOMODCACHE: /go/pkg/mod
      GOCACHE: /root/.cache/go-build
      GOFLAGS: -modcacherw
    volumes:
      # host resources the container needs
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
      # host repo
      - ./:/workspace

      # separate dir in 
      - ol-state:/var/ol

      # cache builds
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    ports:
      - "5000:5000"
volumes:
  ol-state:
  go-mod-cache:
  go-build-cache: